modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"


[[mods]]
modId="dev"
version="1.0.0"
displayName="dev"
authors="Sviluppatore"
description='''dev mod for Minecraft 1.20.1'''


[[dependencies.dev]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"


[[dependencies.dev]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"